version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "audax_datasheets"
      POSTGRES_PASSWORD: "strapi"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ecosystem-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - ecosystem-network

networks:
  ecosystem-network:
    driver: bridge
